fix issue in _get_router_interface
In Pike, the get_network() method tries to update the MTU for the
network if it is NULL but then it tries to do so with DB
writer context while the _get_router_interface() method invokes it with
DB reader context. This results in the following exception:

TypeError: Can't upgrade a READER transaction to a WRITER
mid-transaction

Change-Id: I6d1ffc75b3ed33113459f676494848b3b4c88038
Closes-Bug: #1762953